"""add c2c and duplicate for dial vpn settings.

Revision ID: 313c830f061c
Revises: None
Create Date: 2014-09-28 10:56:29.542570

"""

# revision identifiers, used by Alembic.
revision = '313c830f061c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dial_settings', sa.Column('c2c', sa.Boolean(), nullable=True))
    op.add_column('dial_settings', sa.Column('duplicate', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dial_settings', 'duplicate')
    op.drop_column('dial_settings', 'c2c')
    ### end Alembic commands ###
